name: Enable Auto Merge

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  pull-requests: write
  contents: write

jobs:
  enable-automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Enable Auto Merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
